### ISSUE TITLE
There is no "libcudagrind.so" after 'make new' 

### ISSUE THREAD

**Issue by furuame** [dpc-grindland/Cudagrind#4]
Hi, I cannot find "libcudagrind.so" and "libcuda.so" but "libcudaWrap.so" in current directory after compiling.

Only I modify is path pointing to valgrind and cuda in Makefile, then execute 'make new'.

Could you give any suggestion?

**Comment by wdv4758h** [comment]
First, I'm not the author of Cudagrind. I was surveying something with Valgrind, and I spend some time collect the related projects I found.

I think the result of this current source code is `libcudaWrap.so`, probably try to use it as `libcudagrind.so`. For the `libcuda.so`, it should be provided by the vendor or you system package, path will probably look like this `/opt/cuda/lib64/stubs/libcuda.so`.

**Comment by wdv4758h** [comment]
I'm not sure if the original authors are still developing this project. Let me know if they have updated code, or even @chenweiii you want to help clean up the code and update something.

**Comment by furuame** [comment]
I just find there is an example and I will give it a try in these days. 

Sorry I had not noticed that you are not the author and very thankful for your reply.

**Comment by wdv4758h** [comment]
> I just find there is an example and I will give it a try in these days.

Cool, are you doing research ?

> Sorry I had not noticed that you are not the author and very thankful for your reply.

That's totally fine, I didn't put an `unofficial` mark, and it's good to know someone is working on Valgrind stuff.

**Comment by furuame** [comment]
Yeah, I recently find a Convolutional Neural Network implementation (handcrafted by CUDA.) 

So I want to find some tools to realize its GPU DRAM performance.
